Assignment4-AndreePaul
IntelliTect-Samples/EWU-CSCD371-2024-Winter pull request #114
Opened 2024-02-05 19:52 UTC by Aramirez61

@aramirez61 @pja6
Andree Ramirez and Paul Aguilar

2024-02-07 19:47 UTC, alyxadarr commented
reviewing :)

2024-02-08 00:23 UTC, alyxadarr commented on Logger/EmployeeRecord.cs
> +
I see your BookRecord has a ToString method but your student and employee don't. I am not sure why they don't or you left them out for a reason but you could add the ToString method in these classes.

2024-02-08 00:24 UTC, alyxadarr commented on Logger/EmployeeRecord.cs
> +
```public override string ToString() => base.ToString();
```

2024-02-08 00:25 UTC, alyxadarr commented on Logger/StudentRecord.cs
> +
```
public override string ToString() => base.ToString();
```

2024-02-08 00:27 UTC, alyxadarr commented on Logger.Tests/FullNameRecordTests.cs
> +        public void FullNameRecord_WithNullFirstName_ShouldThrowArgumentNullException()
good job with these tests!

2024-02-08 00:35 UTC, alyxadarr commented on Logger.Tests/StorageTests.cs
> +            Assert.False(storage.Contains(entity));
You could also test for a Get method in storage. You could add a new entity student record and do a-
 var testGuid = Guid.NewGuid();
 IEntity student = new StudentRecord("Paul", "Aguilar")
 {
     Id = testGuid,
 };
 Guid studentGuid = student.Id;
 storage.Add(student);

 IEntity copy = storage.Get(studentGuid)!;
 Assert.NotNull(copy);
 Assert.Equal(student, copy);
}
this could up your code coverage and provide more testing if you want :)

2024-02-08 00:37 UTC, alyxadarr commented on Logger.Tests/FullNameRecordTests.cs
> +
this is a general suggestion for more Testing! We had over 8 testing files (I know a lot) but you could create Test files for EmployeeRecordTests and StudentRecordTests and BookRecordTests. This will get you guys a bigger code coverage and ensure those classes behave the way you need them too.

2024-02-08 00:39 UTC, alyxadarr commented on Logger/PersonName.cs
> +    }
perhaps a ToString method here as well?

2024-02-08 00:39 UTC, alyxadarr commented on Logger/PersonName.cs
> +    }
```
public override string ToString() => Name.ToString();
```

2024-02-08 00:48 UTC, alyxadarr commented on Logger/BookRecord.cs
> +    public override string Name { get => $"{nameof(BookRecord)}:{Author}, {Title}"; }
just wanted to share how we did the name property in each class     
public string Name { get => $"{nameof(Book)}: {Title} By {Author}"; }

2024-02-08 00:50 UTC, alyxadarr commented on Logger/StudentRecord.cs
> +    //common code for name refactored into PersonName that also inherits from base entity
string IEntity.Name {get => $"{nameof(Student)}: {Name}"; }
for the name implementation

2024-02-08 00:50 UTC, alyxadarr commented on Logger/EmployeeRecord.cs
> +    //common code for name refactored into PersonName that also inherits from base entity
string IEntity.Name {get=> $"{nameof(Employee)}: {Name}"; }

2024-02-08 00:56 UTC, alyxadarr requested changes
Define a full name record (first, last, middle) handling optional and null appropriately. ✔
Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
Provide a comment on the full name record on why or why not the type is immutable. ✔
Define an IEntity interface: ✔
Add an Id property of type Guid that is an init-only setter. ✔
Add a Name property that is string. ✔
Define an abstract base class that implements IEntity - appropriately choosing to implement the interface explicitly or implicitly. ✔
Do not implement the Name property in this abstract class. ✔
Do force any derived classes to provide an implementation for Name. ✔
Define book, student, and employee records - all with entity capabilities. ✔
Choose a thoughtful approach for the value of Name for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ❌ see suggestions!
Provide a comment on each interface member in each entity explaining why you implemented it implicitly or explicitly. ✔
You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔
Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
Test that the equality behavior on these entities behaves as expected. ❌ more tests in suggestions
Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
Unit test the Storage class using various entities to ensure that there are no bugs. check
Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.) no TODO comments
Fundamentals
Be sure you enable:
Enable Nullability for all projects ❌ no nullable on Logger.Tests.csproj
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ❌ need <TargetFramework>net8.0</TargetFramework>
on Logger.Tests.csproj
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
Ensure that you turn on EnforceCodeStyleInBuild ✔
Ensure that you turn on Nullability (Nullable) ✔
Ensure there are no errors or warnings (including code analysis warnings) ✔
All of the above should be unit tested ✔

2024-02-08 07:37 UTC, Joshua-Pedersen reviewed
Overall code looks good, however you have minimal testing on your ``StorageTests.cs`` (see comment) and no code coverage for your entities themselves. Be sure to test the equality of different entities of the same time when you do so.

## Tasks

- Define a full name record (first, last, middle) handling optional and null appropriately. ✔
  - Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
  - Provide a comment on the full name record on why or why not the type is immutable. ✔
- Define an `IEntity` interface: ✔
  - Add an Id property of type `Guid` that is an init-only setter. ✔
  - Add a Name property that is `string`. ✔
- Define an abstract base class that implements `IEntity` - appropriately choosing to implement the interface explicitly or implicitly. ✔
  - Do not implement the `Name` property in this abstract class. ✔
  - Do force any derived classes to provide an implementation for `Name`. ✔
- Define book, student, and employee records - all with entity capabilities. ✔
  - Choose a thoughtful approach for the value of `Name` for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
  - Provide a comment on each interface **member** in each entity explaining why you implemented it implicitly or explicitly. ✔
  - You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔
  - Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
  - Test that the equality behavior on these entities behaves as expected. ❌ 
  - Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
- Unit test the Storage class using various entities to ensure that there are no bugs.
- Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.)
  - Pay special attention to the CreateLogger methods throughout.

## Fundamentals

- Be sure you enable:
  - Enable Nullability for all projects  ✔
  - Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ✔
  - Ensure that you turn on code analysis for all projects(`EnableNETAnalyzers`) ✔
  - Ensure that you turn on `EnforceCodeStyleInBuild` ✔
  - Ensure that you turn on Nullability (`Nullable`) ✔
- **Ensure there are no errors or warnings (including code analysis warnings)** ✔
- **All of the above should be unit tested** ❌
- **Choose simplicity over complexity** ✔

## Extra Credit

- Refactor your project files to put common properties and/or items into a single file. ❌
- Convert `ILogger.CreateLogger` to a generic method. ❌
  - Returns the logger classes type that is to be created. ❌
  - Has a type parameter for the configuration type ❌

2024-02-08 07:37 UTC, Joshua-Pedersen commented on Logger.Tests/StorageTests.cs
> +        }
Akin to what alyxadarr said, there is no test for ``Get``. Also the doc specifies ``...test the Storage class using various entities...`` personally I just made 3 ``Add``, ``Remove``, and ``Get`` tests to ensure each entity is covered.

2024-02-08 07:37 UTC, Joshua-Pedersen commented on Logger/BookRecord.cs
> +using System.Threading.Tasks;
You don't need these ``Using`` statements, doesn't effect anything but makes for cleaner code. A few other classes have these as well.

2024-02-08 07:37 UTC, Joshua-Pedersen commented on Logger/BookRecord.cs
> +    public string Author { get; set; } = Author ?? throw new ArgumentNullException(nameof(Title));
Unsure but I assume you meant ``nameof(Author)`` here

2024-02-08 18:19 UTC, pja6 commented on Logger/BookRecord.cs
> +    public string Author { get; set; } = Author ?? throw new ArgumentNullException(nameof(Title));
Definitely did - thanks!

2024-02-08 18:41 UTC, pja6 commented on Logger/EmployeeRecord.cs
> +
Oh thanks! - this fixed some tests, thanks!

2024-02-08 18:43 UTC, pja6 commented on Logger/EmployeeRecord.cs
> +
updated

2024-02-08 18:45 UTC, pja6 commented on Logger/StudentRecord.cs
> +
updated

2024-02-08 18:45 UTC, pja6 commented on Logger/PersonName.cs
> +    }
updated

2024-02-08 18:45 UTC, pja6 commented on Logger/PersonName.cs
> +    }
updated

2024-02-08 18:48 UTC, pja6 commented
> Define a full name record (first, last, middle) handling optional and null appropriately. ✔ Provide a comment on the full name record on why you selected to define a value or a reference type and ✔ Provide a comment on the full name record on why or why not the type is immutable. ✔ Define an IEntity interface: ✔ Add an Id property of type Guid that is an init-only setter. ✔ Add a Name property that is string. ✔ Define an abstract base class that implements IEntity - appropriately choosing to implement the interface explicitly or implicitly. ✔ Do not implement the Name property in this abstract class. ✔ Do force any derived classes to provide an implementation for Name. ✔ Define book, student, and employee records - all with entity capabilities. ✔ Choose a thoughtful approach for the value of Name for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ❌ see suggestions! Provide a comment on each interface member in each entity explaining why you implemented it implicitly or explicitly. ✔ You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔ Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔ Test that the equality behavior on these entities behaves as expected. ❌ more tests in suggestions Provide a comment on each interface method explaining why you implemented it implicitly or explicitly. Unit test the Storage class using various entities to ensure that there are no bugs. check Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.) no TODO comments Fundamentals Be sure you enable: Enable Nullability for all projects ❌ no nullable on Logger.Tests.csproj Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ❌ need net8.0 on Logger.Tests.csproj Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔ Ensure that you turn on EnforceCodeStyleInBuild ✔ Ensure that you turn on Nullability (Nullable) ✔ Ensure there are no errors or warnings (including code analysis warnings) ✔ All of the above should be unit tested ✔

-nullable and current .net version are applied in test csproj file, just hidden by github, was confusing but is viewable if you click on "expand up"

2024-02-08 19:03 UTC, Aramirez61 commented on Logger.Tests/FullNameRecordTests.cs
> +
Thanks for the suggestion! Went ahead and added these test files. I agree its important to make sure we cover our code well. Ended up finding out that our toStrings were not working as intended, so thanks once again!

2024-02-08 19:06 UTC, Aramirez61 commented on Logger.Tests/FullNameRecordTests.cs
> +        public void FullNameRecord_WithNullFirstName_ShouldThrowArgumentNullException()
Thanks!

2024-02-08 19:21 UTC, pja6 commented on Logger/BookRecord.cs
> +using System.Threading.Tasks;
True, I'm always wary about removing directives that are already there, this makes sense

2024-02-08 19:31 UTC, pja6 commented on Logger/StudentRecord.cs
> +    //common code for name refactored into PersonName that also inherits from base entity
I wasn't sure if this was applicable since we didn't implement name explicitly

2024-02-08 19:34 UTC, pja6 commented on Logger/BookRecord.cs
> +    public override string Name { get => $"{nameof(BookRecord)}:{Author}, {Title}"; }
Thanks! - i think they're pretty similar, just different formatting

2024-02-08 22:14 UTC, Aramirez61 commented on Logger.Tests/StorageTests.cs
> +            Assert.False(storage.Contains(entity));
Went ahead and added a test for the get method! Thanks for catching that.

2024-02-08 22:15 UTC, Aramirez61 commented on Logger/EmployeeRecord.cs
> +    //common code for name refactored into PersonName that also inherits from base entity
We ended up overriding toString in our get employee and student class.

2024-02-08 22:16 UTC, Aramirez61 commented on Logger.Tests/StorageTests.cs
> +        }
We added a test for the get method and tested it with more than 1 of the entities this time, thanks for the reminder!

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger.Tests/StorageTests.cs
> +            Assert.False(storage.Contains(entity));
```suggestion
            Assert.DoesNotContain(entity, storage);
```
I think Assert.Contains might be slightly easier.

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger.Tests/StorageTests.cs
> +            Assert.True(storage.Contains(entity));
```suggestion
            Assert.Contains(entity, storage);
```
Assert.Contains may be easier here

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger.Tests/StudentRecordTests.cs
> +        Assert.Equal("Jane Doe Smith", result);
```suggestion
        Assert.Equal("Jane Doe Smith", student.ToString());
```
In-lining the temporary variable

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger.Tests/StudentRecordTests.cs
> +}
```suggestion
    }
}
```
nit: lots of blank space

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger/BaseEntity.cs
> +    }
```suggestion
        public abstract string Name { get; }
```
Making this one line might be a bit more clear.

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger/BaseEntity.cs
> +         Guid IEntity.Id { get => _InternalId; init => _InternalId = value; }
Why is a backing field needed? Would something like this work?

Additionally, I would expect the ID maybe wants to be set by the parent? But it could probably be argued either way.

```suggestion
        //because this is an internal ID used by developers and not the same as an employee or student id it is implemented explicitly
         Guid IEntity.Id { get;  } = Guid.NewGuid();    
```

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger/BookRecord.cs
> +public record class BookRecord ( string Author, string Title, int Isbn) : BaseEntity(Guid.NewGuid())
We know it's a record because it is a record class, keeping it just as like `Book` may be simpler and more clear to the object itself. What is a `BookRecord`? But a `Book` is a thing, record is just the type that it's being stored by
```suggestion
public record class Book ( string Author, string Title, int Isbn) : BaseEntity(Guid.NewGuid())

```

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger/FullNameRecord.cs
> +        }
```suggestion
        public FullNameRecord(string firstName, string lastName, string? middleName = null)
        {
            FirstName = firstName ?? throw new ArgumentNullException(nameof(firstName));
            LastName = lastName ?? throw new ArgumentNullException(nameof(lastName));
            MiddleName = middleName;
        }
```

I think using a default value would allow you to keep the same functionality without breaking existing code.

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger/IEntity.cs
> +    }
```suggestion
        string Name { get; }
```
One line is more clear

2024-02-12 05:49 UTC, BenjaminMichaelis commented on Logger.Tests/FullNameRecordTests.cs
> +        Assert.Equal(expected, result);
With the new FullName constructor I mentioned in another comment, you wouldn't need a conditional in this test

2024-02-12 06:18 UTC, BenjaminMichaelis commented on .DS_Store
This should be added to the .gitignore file and not committed into the repo

2024-02-13 18:15 UTC, StrangeRanger commented on Logger/BookRecord.cs
> +using System.Threading.Tasks;
@pja6 The IDE should let you know when they aren't needed, usually by greying them out.

2024-02-20 21:48 UTC, closed without merging