Assignment6 - Ethan Guerin and Ethan Florko
IntelliTect-Samples/EWU-CSCD371-2024-Winter pull request #147
Opened 2024-02-20 04:15 UTC by EthanAGi

@EthanAGi @EthanFlorko

2024-02-22 00:37 UTC, alyxadarr requested changes
good job on the assignment! just a couple of minor fixes 
Create a Console project called "Calculate.". ✔
Define a Program Class
Define two init-only setter properties, WriteLine and ReadLine, that contain delegates for writing a line of text and reading a line of text respectively ✔
Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ❌  
Set the default behavior for the WriteLine and ReadLine properties to invoke System.Console versions of the methods and add an empty default constructor. ✔
Define a Calculator class ✔
Define static Add, Subtract, Multiple, and Divide methods that have two parameters and return a third parameter. ✔ the assignment says Multiple but everyone is doing Multiply xD
Define a read-only property, MathematicalOperations, of type System.Collections.Generics.IReadOnlyDictionary<TKey,TValue> that:
is initialized to a System.Collections.Generics.Dictionary<<TKey,TValue> instance that. ❌
Uses char for the key corresponding to the operators +, -, *, and /. ✔
Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
Implement a TryCalculate method following "TryParse" pattern ✔
Valid calculation expressions include such strings as "3 + 4", "42 - 2", etc. ✔
If there is no whitespace around the operator, you can assume the calculation is invalid and return false. Similarly if the operands are not integers. ✔
Use string.Split(), pattern matching, logical and operators to parse the string in their entirety ✔
Index into the MathematicalOperations method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ✔
Be sure to use the WriteLine/ReadLine properties on Program for testing the input and output of your program. ❌ need ReadLine test in program tests
Fundamentals
Place all shared project properties into a Directory.Build.Props file.
Place all shared project items into a Directory.Build.targets file.
nullable reference types is enabled ✔
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
and enabled .NET analyzers for both projects ✔
For this assignment, always use Assert.AreEqual<T>() (the generic version) ✔

2024-02-22 00:37 UTC, alyxadarr commented on Calculate/Calculate/Calculator.cs
> +        if (!int.TryParse(parts[0], out int lhs) || !int.TryParse(parts[2], out int rhs)) return false;
Nice job using TryParse and TryGetValue!

2024-02-22 00:37 UTC, alyxadarr commented on Calculate/Calculate/Calculator.cs
> +    public static int Add(int a, int b) => a + b;
a suggestion could be to change the return to a double to be more precise in the program but we used int as well! just something I noticed!

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Calculator.Tests.cs
> +    public void Add_CorrectData_ReturnsAdd(int a, int b, int ans)
great job on these tests! Very readable and efficient

2024-02-22 00:37 UTC, alyxadarr commented on Calculate/Calculate/Calculator.cs
> +        if (b == 0)
good job on testing for the divide by 0 case. We did not implement this so this is a great idea!

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Calculator.Tests.cs
> +    {
Great job testing for the divide by zero case! I want to add this to our tests

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Program.Tests.cs
> +        Assert.Equal(expOotput, ootput);
maybe add a Test that tests for the invalid expression line? just to make sure it does invoke that but otherwise good job

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Program.Tests.cs
> +    {
I think you also need a Test to test the constructor behavior per the assignment instructions. "Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs"

2024-02-22 00:37 UTC, alyxadarr commented on Calculate/Calculate/Calculator.cs
> +        new Dictionary<char, Func<int, int, int>>
I think IReadOnlyDictionary<char, Func<T, T, T>> MathematicalOperations { get; } = new Dictionary<char, Func<T, T, T>>  needs to be implemented instead via the assignment specifications ? this looks like a readonly type that isnt the generic.

2024-02-22 00:37 UTC, alyxadarr commented on Calculate/Calculate/Calculator.cs
> +    public static int Add(int a, int b) => a + b;
reading the assignment specifications over and it does mention integers so i think we are safe. probably an iffy suggestion lol

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Program.Tests.cs
> +public class ProgramTests
you need to use readline for testing the program per the assignment instructions. they mention both readLine and Writeline but you only used WriteLine

2024-02-22 00:37 UTC, alyxadarr commented on Calculate.Tests/Program.Tests.cs
> +public class ProgramTests
we used a constructor on our tests to make it simpler and easier     
DefaultProgram = new Program();
        InitProgram = new Program()
        {
            ReadLine = FileReadLine,
            WriteLine = FileWriteLine
        };    
    }

2024-02-22 05:07 UTC, rkdeboer reviewed
good job on the assignment! just a couple of minor fixes
Create a Console project called "Calculate.". ✔
Define a Program Class
Define two init-only setter properties, WriteLine and ReadLine, that contain delegates for writing a line of text and reading a line of text respectively ✔
Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ❌
Set the default behavior for the WriteLine and ReadLine properties to invoke System.Console versions of the methods and add an empty default constructor. ✔
Define a Calculator class ✔
Define static Add, Subtract, Multiple, and Divide methods that have two parameters and return a third parameter. ✔ 
Define a read-only property, MathematicalOperations, of type System.Collections.Generics.IReadOnlyDictionary<TKey,TValue> that:
is initialized to a System.Collections.Generics.Dictionary<<TKey,TValue> instance that. ❌
Uses char for the key corresponding to the operators +, -, *, and /. ✔
Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
Implement a TryCalculate method following "TryParse" pattern ✔
Valid calculation expressions include such strings as "3 + 4", "42 - 2", etc. ✔
If there is no whitespace around the operator, you can assume the calculation is invalid and return false. Similarly if the operands are not integers. ✔
Use string.Split(), pattern matching, logical and operators to parse the string in their entirety ✔
Index into the MathematicalOperations method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ✔
Be sure to use the WriteLine/ReadLine properties on Program for testing the input and output of your program. ❌ 
Fundamentals
Place all shared project properties into a Directory.Build.Props file.
Place all shared project items into a Directory.Build.targets file.
nullable reference types is enabled ✔
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
and enabled .NET analyzers for both projects ✔
For this assignment, always use Assert.AreEqual() (the generic version) ✔

2024-02-22 05:07 UTC, rkdeboer commented on Calculate.Tests/Calculator.Tests.cs
> +    [InlineData(0, 0, 0)]
Great use of the Inline data

2024-02-22 05:07 UTC, rkdeboer commented on Calculate/Calculate/Calculator.cs
> +        if (b == 0)
Yes truly a good catch on that one. I forgot about that for sure!

2024-02-22 05:07 UTC, rkdeboer commented on Calculate/Calculate/Program.cs
> +            program.WriteLine($"Result: {result}");
This is a cool way of doing it. I think Matt and I put ours in a while loop but that is a great way to do it too

2024-02-22 05:07 UTC, rkdeboer commented on Calculate.Tests/Calculator.Tests.cs
> +    [InlineData("4 # 5", false)]
Great testing for invalid expressions

2024-03-05 16:15 UTC, BenjaminMichaelis commented on Calculate.Tests/Program.Tests.cs
> +        string ootput = "";
```suggestion
        string expOutput = "Nah, I'd win.";
        string output = "";
```
nit: spelling

2024-03-05 16:15 UTC, BenjaminMichaelis commented on Calculate/Calculate/Calculate.csproj
> +	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
These should all be moved into a shared props file

2024-03-05 16:15 UTC, BenjaminMichaelis commented on Calculate/Calculate/Calculator.cs
> +            throw new ArgumentException("Cannot Divide by Zero.");
Divide by zero by default throws a `System.DivideByZeroException`

2024-03-06 23:00 UTC, closed without merging