Assignment2 Andree Hadi
IntelliTect-Samples/EWU-CSCD371-2024-Winter pull request #72
Opened 2024-01-23 06:12 UTC by HadiM2

2024-01-23 06:23 UTC, HadiM2 commented
Why is build failing?

2024-01-25 00:01 UTC, EthanAGi commented
Reviewing

2024-01-25 00:45 UTC, EthanAGi requested changes
- There is an existing `BaseLogger` class. It needs an **auto property** to hold a class name. This property should be set in the `LogFactory` using an **object initializer**. ✔
- Create a `FileLogger` that derives from `BaseLogger`. It should take in a path to a file to write the log message to. When its `Log` method is called, it should **append** messages on their own line in the file. The output should include all of the following:
  - The current date/time ❌ <- The fix for this is indicated in the comments!
  - The name of the class that created the logger ✔
  - The log level ✔
  - The message ✔
  - The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
- The `LogFactory` should be updated with a new method `ConfigureFileLogger`. This should take in a file path and store it in a **private member**. It should use this when instantiating a new `FileLogger` in its `CreateLogger` method. ✔
- If the file logger has not be configured in the `LogFactory`, its `CreateLogger` method should return `null`. ✔
- Inside of `BaseLoggerMixins` implement **extension methods** on `BaseLogger` for
  - `Error`, ✔
  - `Warning`, ✔
  - `Information`, and ✔
  - `Debug`. ✔
  Each of these methods should take in a `string` for the message, as well as a **parameter array** of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the `BaseLogger.Log` method, by automatically supplying the appropriate `LogLevel`. These methods should throw an exception if the `BaseLogger` parameter is null. There are a couple example unit tests to get you started.
- Use the nameof() operator when identifying the class name to the logger ✔
- Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
- Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
- Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
- Ensure that you turn on EnforceCodeStyleInBuild ✔
- Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ✔
- Turn on Nullability (`Nullable`) ✔

Nicely done! I can tell you get what's going on here, and with just a few tweaks, I think you'll be there! Well done!

2024-01-25 00:45 UTC, EthanAGi commented on Logger/FileLogger.cs
> +    string filePath;
changing this to a private, readonly field will fix this error.

2024-01-25 00:45 UTC, EthanAGi commented on Logger/BaseLoggerMixins.cs
> +            baseLogger.Log(LogLevel.Debug, string.Format(message, arguments));
changing this to an IFormatProvider where indicated will elminate this error. What it is worried about is that this string needs to be formatted for different machines. A recommendation from me would be CultureInfo.InvariantCulture, as this fomrats strings to the users machine.

2024-01-25 00:45 UTC, EthanAGi commented on Logger/LogFactory.cs
> +            FileLogger fileLogger = new FileLogger(filePath) { ClassName = className};
Here, if we use "FileLogger filelogger = new(filePath)" here, the Error will be removed. This is because in C#, Not using the class type next to new is the standard.

2024-01-25 00:45 UTC, EthanAGi commented on Logger/FileLogger.cs
> +        string dateTime = System.DateTime.Now.ToString("M/d/yyyy hh:mm:ss tt");
We can replace this entire String by placing "DateTime.Now" into our call for logEntry. 
string logEntry = $"{DateTime.Now} {nameof(this.ClassName)} {logLevel}: {message}";
That worked form me, but I'm not too sure if that will directly fix the error.

2024-01-25 00:45 UTC, EthanAGi commented on Logger/BaseLoggerMixins.cs
> +            baseLogger.Log(LogLevel.Information, string.Format(message, arguments));
Placing the IFormatProvider into this Line will also fix it.

2024-01-26 06:00 UTC, HadiM2 commented on Logger/BaseLoggerMixins.cs
> +            baseLogger.Log(LogLevel.Debug, string.Format(message, arguments));
Thank you that worked!

2024-01-26 06:00 UTC, HadiM2 commented on Logger/LogFactory.cs
> +            FileLogger fileLogger = new FileLogger(filePath) { ClassName = className};
OHHH it was because of the treat warnings as error, good catch!

2024-01-26 06:01 UTC, Aramirez61 commented on Logger/FileLogger.cs
> +        string dateTime = System.DateTime.Now.ToString("M/d/yyyy hh:mm:ss tt");
Thank you, that did it and fixed the error we were getting.

2024-01-26 06:03 UTC, Aramirez61 commented on Logger/BaseLoggerMixins.cs
> +            baseLogger.Log(LogLevel.Information, string.Format(message, arguments));
Thank you, we used string.Format(CultureInfo.InvariantCulture, message, args) and that fixed it

2024-01-30 05:32 UTC, BenjaminMichaelis commented on .DS_Store
I would disclude these files from your commit's by putting them in your .gitignore

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger.Tests/Logger.Tests.csproj
> +	</PropertyGroup>
It looks like you are missing a few elements here. Ex: TreatWarningsAsErrors

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger/BaseLogger.cs
> +    public string? ClassName {get; set;}
Why is this nullable?

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger/FileLogger.cs
> +    private readonly string filePath;
This should be a property

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger/FileLogger.cs
> +        this.filePath = filePath;
If you have to use `this` it indicates you are missing a naming convention. The field you are referencing should have a leading `_`

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger/LogFactory.cs
> +        ConfigureFileLogger(filePath);
The logger should either be configured or not at this point. I don't see the logic in calling this method

2024-01-30 05:32 UTC, BenjaminMichaelis commented on Logger/Logger.csproj
> +    <NetAnalyzers>true</NetAnalyzers>
This should be `EnableNETAnalyzers`

2024-01-30 21:42 UTC, closed without merging