Assignment 2 - Kyle Wong
IntelliTect-Samples/EWU-CSCD371-2024-Winter pull request #78
Opened 2024-01-23 07:53 UTC by KairyuSen

I think I have my errors, but I know I don't have a lot, got lost on tests.

2024-01-24 23:09 UTC, EthanAGi commented
Reviewing

2024-01-24 23:42 UTC, EthanAGi requested changes
Hey so, I'm not sure if something went wrong on my end, but the files on GitHub look generally the same. As far as I can tell, only the BaseLoggerMixinsTest was written, but if there has been an error let me know.

The Null error is coming from the fact that the classes aren't set to Nullable. This can be done by heading into the .csproj file and changing the Property Group to be Nullable. This is also where we change the options that allow our code analyzers and Treating warnings as errors. The .csproj file is also where we need to set our language and .net version.

When writing the Classes, keep in mind Nullability, as that was the thing that kept tripping me on the lab. When debugging, keep an eye on where your variables are going and WHERE the errors are being tripped, as sometimes that can help you figure out where the problems are happening. Good Luck!

- There is an existing `BaseLogger` class. It needs an **auto property** to hold a class name. This property should be set in the `LogFactory` using an **object initializer**. ❌
- Create a `FileLogger` that derives from `BaseLogger`. It should take in a path to a file to write the log message to. When its `Log` method is called, it should **append** messages on their own line in the file. The output should include all of the following:
  - The current date/time ❌
  - The name of the class that created the logger ❌
  - The log level ❌
  - The message ❌
  - The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
- The `LogFactory` should be updated with a new method `ConfigureFileLogger`. This should take in a file path and store it in a **private member**. It should use this when instantiating a new `FileLogger` in its `CreateLogger` method. ❌
- If the file logger has not be configured in the `LogFactory`, its `CreateLogger` method should return `null`. ❌ 
- Inside of `BaseLoggerMixins` implement **extension methods** on `BaseLogger` for
  - `Error`, ❌
  - `Warning`, ❌
  - `Information`, and ❌
  - `Debug`. ❌
  Each of these methods should take in a `string` for the message, as well as a **parameter array** of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the `BaseLogger.Log` method, by automatically supplying the appropriate `LogLevel`. These methods should throw an exception if the `BaseLogger` parameter is null. There are a couple example unit tests to get you started.
- Use the nameof() operator when identifying the class name to the logger ❌
- Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ❌
- Ensure that you turn on code analysis (EnableNETAnalyzers) ❌
- Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ❌
- Ensure that you turn on EnforceCodeStyleInBuild ❌
- Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ❌
- Turn on Nullability (`Nullable`) ❌

2024-01-25 17:36 UTC, MattA41 reviewed
I can only see changes in the BaseLoggerMixinsTest and no other files. Did you do more for the project? I does not look like to did to me
    There is an existing BaseLogger class. It needs an auto property to hold a class name. This property should be set in the LogFactory using an object initializer. ❌
    Create a FileLogger that derives from BaseLogger. It should take in a path to a file to write the log message to. When its Log method is called, it should append messages on their own line in the file. The output should include all of the following:
        The current date/time ❌
        The name of the class that created the logger ❌
        The log level ❌
        The message ❌
        The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
    The LogFactory should be updated with a new method ConfigureFileLogger. This should take in a file path and store it in a private member. It should use this when instantiating a new FileLogger in its CreateLogger method. ❌
    If the file logger has not be configured in the LogFactory, its CreateLogger method should return null. ❌
    Inside of BaseLoggerMixins implement extension methods on BaseLogger for
        Error, ❌
        Warning, ❌
        Information, and ❌
        Debug. ❌ Each of these methods should take in a string for the message, as well as a parameter array of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the BaseLogger.Log method, by automatically supplying the appropriate LogLevel. These methods should throw an exception if the BaseLogger parameter is null. There are a couple example unit tests to get you started.
    Use the nameof() operator when identifying the class name to the logger ❌
    Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ❌
    Ensure that you turn on code analysis (EnableNETAnalyzers) ❌
    Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ❌
    Ensure that you turn on EnforceCodeStyleInBuild ❌
    Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ❌
    Turn on Nullability (Nullable) ❌
    All of the above should be unit tested. ❌

2024-01-25 17:36 UTC, MattA41 commented on Logger.Tests/BaseLoggerMixinsTests.cs
> +        logger.Error("Message 42");
nice fix on this test

2024-01-30 06:28 UTC, BenjaminMichaelis commented on Logger/BaseLoggerMixins.cs
> +    public static void Error_WithNullLogger_ThrowsException(this BaseLogger? logger, string message, params object[] args)
This can be just called `Error`. Same applies for other methods.

```suggestion
    public static void Error(this BaseLogger? logger, string message, params object[] args)
```

2024-01-30 06:28 UTC, BenjaminMichaelis commented on Logger/BaseLoggerMixins.cs
> +    public static void Warning_WithNullLogger_ThrowsException(this BaseLogger? logger, string message, params object[] args)
Why is logger nullable? I expect to call this message, a logger is needed.

2024-01-30 06:28 UTC, BenjaminMichaelis commented on Logger/LogFactory.cs
> +        ConfigureFileLogger(FilePath);
Why are you calling this here?

2024-01-30 06:28 UTC, BenjaminMichaelis commented on Logger/LogFactory.cs
> +            FileLogger logger = new(FilePath) { ClassName = className };
Why are you casting this?

2024-01-30 06:28 UTC, BenjaminMichaelis commented on Logger/LogFactory.cs
> +    }
What are these for?

2024-01-30 21:42 UTC, closed without merging